#   ,--,                                                                                                          
#,---.'|                                                             ,-.----.                                     
#|   | :                                                    ,---,    \    /  \                                    
#:   : |                                                  ,--.' |    |   :    \                 ,---,             
#|   ' :                        ,--,      ,---,           |  |  :    |   |  .\ :              ,---.'|             
#;   ; '                      ,'_ /|  ,-+-. /  |          :  :  :    .   :  |: |              |   | :  .--.--.    
#'   | |__   ,--.--.     .--. |  | : ,--.'|'   |   ,---.  :  |  |,--.|   |   \ : ,--.--.      |   | | /  /    '   
#|   | :.'| /       \  ,'_ /| :  . ||   |  ,"' |  /     \ |  :  '   ||   : .   //       \   ,--.__| ||  :  /`./   
#'   :    ;.--.  .-. | |  ' | |  . .|   | /  | | /    / ' |  |   /' :;   | |`-'.--.  .-. | /   ,'   ||  :  ;_     
#|   |  ./  \__\/: . . |  | ' |  | ||   | |  | |.    ' /  '  :  | | ||   | ;    \__\/: . ..   '  /  | \  \    `.  
#;   : ;    ," .--.; | :  | : ;  ; ||   | |  |/ '   ; :__ |  |  ' | ::   ' |    ," .--.; |'   ; |:  |  `----.   \ 
#|   ,/    /  /  ,.  | '  :  `--'   \   | |--'  '   | '.'||  :  :_:,':   : :   /  /  ,.  ||   | '/  ' /  /`--'  / 
#'---'    ;  :   .'   \:  ,      .-./   |/      |   :    :|  | ,'    |   | :  ;  :   .'   \   :    :|'--'.     /  
#         |  ,     .-./ `--`----'   '---'        \   \  / `--''      `---'.|  |  ,     .-./\   \  /    `--'---'   
#          `--`---'                               `----'               `---`   `--`---'     `----'                
#

#The blocks you want as launchpad
launchpads: [152]
#Strength of launchpad
launchpad-stength: 1
#If enabled, you can change a launchpad's direction by placing a torch the direction you want.
enable-torch-mode: true